# Generated by Django 5.1.6 on 2025-03-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='grupos',
            field=models.ManyToManyField(related_name='proyectos', to='auth.group'),
        ),
    ]
