# Generated by Django 5.1.6 on 2025-03-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_proyecto_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='auth_group',
        ),
        migrations.AddField(
            model_name='ticket',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.proyecto'),
        ),
    ]
