# Generated by Django 5.1.6 on 2025-03-19 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_auth_group_ticket_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.proyecto'),
        ),
    ]
