# Generated by Django 5.1.6 on 2025-03-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='tickets.ticket'),
        ),
    ]
