# Generated by Django 5.1.6 on 2025-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='multimedia_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
